stages:
  - .pre
  - build_common
  - build_A
#  - .post

## pre
pre_deploy_file:
  stage: .pre
  only:
#    - master
    - dev
  script:
    - zip -r deploy.zip ./deploy/deploy.sh
    # 不同分支 对应 不同变量
    - if [ "${CI_COMMIT_REF_NAME}" == "master" ]; then USER_NAME=${user_master}; else USER_NAME=${user_test}; fi
    - if [ "${CI_COMMIT_REF_NAME}" == "master" ]; then HOST=${host_master}; else HOST=${host_test}; fi
    # 部署
    - scp -P 88 deploy.zip ${USER_NAME}@${HOST}:/opt/coding/wxhg-infectDisMonitor-back/
    - ssh -p 88 ${USER_NAME}@${HOST} "cd /opt/coding/wxhg-infectDisMonitor-back/ ; unzip -o deploy.zip ; rm deploy.zip"

pre_app-monitor_resource:
  stage: .pre
  only:
    refs:
#      - master
      - dev
    changes:
      - app-monitor/**/*
  script:
    - pwd
    - whoami
    # 不同分支 对应 不同变量
    - if [ "${CI_COMMIT_REF_NAME}" == "master" ]; then USER_NAME=${user_master}; else USER_NAME=${user_test}; fi
    - if [ "${CI_COMMIT_REF_NAME}" == "master" ]; then HOST=${host_master}; else HOST=${host_test}; fi
    # 上传所需本地资源
    - cp -r ./app-monitor/src/main/resources/report ./
    - zip -r resource.zip ./report
    - scp -P 88 ./resource.zip ${USER_NAME}@${HOST}:/opt/coding/wxhg-infectDisMonitor-back/app-monitor/
    - ssh -p 88 ${USER_NAME}@${HOST} "cd /opt/coding/wxhg-infectDisMonitor-back/app-monitor ; unzip -o resource.zip ; rm resource.zip"

## build parent
build_parent:
  stage: build_common
  only:
    refs:
#      - master
      - dev
    changes:
      - app-monitor/**/*
      - service-datapack/**/*
      - service-topic/**/*
  script:
    - pwd
    - whoami
    #
    - cd cloud-parent/
    - mvn clean install -Dmaven.test.skip=true
    - cd ../cloud-common/
    - mvn clean install -Dmaven.test.skip=true
    - cd ../
#  artifacts:
#    paths:
#      - ./app-monitor/target/app-monitor-0.0.1-SNAPSHOT.jar
#      - ./service-datapack/target/service-datapack-0.0.1-SNAPSHOT.jar
#      - ./service-topic/target/service-topic-0.0.1-SNAPSHOT.jar


## app-monitor
build_app-monitor:
  stage: build_app
  only:
    refs:
#      - master
      - dev
    changes:
      - app-monitor/**/*
  script:
    - pwd
    - whoami
    # 不同分支 对应 不同变量
    - if [ "${CI_COMMIT_REF_NAME}" == "master" ]; then USER_NAME=${user_master}; else USER_NAME=${user_test}; fi
    - if [ "${CI_COMMIT_REF_NAME}" == "master" ]; then HOST=${host_master}; else HOST=${host_test}; fi
    - if [ "${CI_COMMIT_REF_NAME}" == "master" ]; then BRANCH_NAME="branch-master"; else BRANCH_NAME="branch-test"; fi
    # 后台打包部署
    - cd app-monitor/
    - mvn clean install -Dmaven.test.skip=true
    - cd ../
    - scp -P 88 ./app-monitor/target/app-monitor-0.0.1-SNAPSHOT.jar ${USER_NAME}@${HOST}:/opt/coding/wxhg-infectDisMonitor-back/app-monitor/
    - ssh -p 88 ${USER_NAME}@${HOST} "cd /opt/coding/wxhg-infectDisMonitor-back/ ; bash ./deploy/deploy.sh ${BRANCH_NAME} app-monitor 0.0.1-SNAPSHOT"
  dependencies:
    - build_parent

## service-datapack
build_service-datapack:
  stage: build_data
  only:
    refs:
#      - master
      - dev
    changes:
      - service-datapack/**/*
  script:
    - pwd
    - whoami
    # 不同分支 对应 不同变量
    - if [ "${CI_COMMIT_REF_NAME}" == "master" ]; then USER_NAME=${user_master}; else USER_NAME=${user_test}; fi
    - if [ "${CI_COMMIT_REF_NAME}" == "master" ]; then HOST=${host_master}; else HOST=${host_test}; fi
    - if [ "${CI_COMMIT_REF_NAME}" == "master" ]; then BRANCH_NAME="branch-master"; else BRANCH_NAME="branch-test"; fi
    # 后台打包部署
    - cd service-datapack/
    - mvn clean install -Dmaven.test.skip=true
    - cd ../
    - scp -P 88 ./service-datapack/target/service-datapack-0.0.1-SNAPSHOT.jar ${USER_NAME}@${HOST}:/opt/coding/wxhg-infectDisMonitor-back/service-datapack/
    - ssh -p 88 ${USER_NAME}@${HOST} "cd /opt/coding/wxhg-infectDisMonitor-back/ ; bash ./deploy/deploy.sh ${BRANCH_NAME} service-datapack 0.0.1-SNAPSHOT"
  dependencies:
    - build_parent

## service-topic
build_service-topic:
  stage: build_topic
  only:
    refs:
#      - master
      - dev
    changes:
      - service-topic/**/*
  script:
    - pwd
    - whoami
    # 不同分支 对应 不同变量
    - if [ "${CI_COMMIT_REF_NAME}" == "master" ]; then USER_NAME=${user_master}; else USER_NAME=${user_test}; fi
    - if [ "${CI_COMMIT_REF_NAME}" == "master" ]; then HOST=${host_master}; else HOST=${host_test}; fi
    - if [ "${CI_COMMIT_REF_NAME}" == "master" ]; then BRANCH_NAME="branch-master"; else BRANCH_NAME="branch-test"; fi
    # 后台打包部署
    - cd service-topic/
    - mvn clean install -Dmaven.test.skip=true
    - cd ../
    - scp -P 88 ./service-topic/target/service-topic-0.0.1-SNAPSHOT.jar ${USER_NAME}@${HOST}:/opt/coding/wxhg-infectDisMonitor-back/service-topic/
    - ssh -p 88 ${USER_NAME}@${HOST} "cd /opt/coding/wxhg-infectDisMonitor-back/ ; bash ./deploy/deploy.sh ${BRANCH_NAME} service-topic 0.0.1-SNAPSHOT"
  dependencies:
    - build_parent

build_A:
  stage: build_A
  dependencies:
      - build_app
      - build_data
      - build_topic
### post
#post_deploy_file:
#  stage: .post
#  only:
##    - master
#    - dev
#  script:
#    - pwd
#    - whoami
#    # 不同分支 对应 不同变量
#    - if [ "${CI_COMMIT_REF_NAME}" == "master" ]; then USER_NAME=${user_master}; else USER_NAME=${user_test}; fi
#    - if [ "${CI_COMMIT_REF_NAME}" == "master" ]; then HOST=${host_master}; else HOST=${host_test}; fi
#    - ssh -p 88 ${USER_NAME}@${HOST} "cd /opt/coding/wxhg-infectDisMonitor-back/ ; rm deploy.zip"
