# Server configuration
server:
  port: 8071

spring:
  application:
    name: service-datapack
  profiles:
    active: dev

#######
# dev #
#######
---
spring:
  profiles: dev


logging:
  file: logs/${spring.application.name}.log
  level:
    root: Error




#######
# test #
#######
---
spring:
  profiles: test


logging:
  file: logs/${spring.application.name}.log
  level:
    root: Info
    org.springframework: Debug
    com.dataint: Debug


########
# prod #
########
---
spring:
  profiles: prod

logging:
  file: logs/${spring.application.name}.log
  level:
    root: Info
    org.springframework: Info
    com.dataint: Info